name: CI
on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
    tags: '*'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - default
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip' # Automatically caches installed packages for faster subsequent runs
      - name: Install scikit-learn, python library
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Build Julia package deps
        uses: julia-actions/julia-buildpkg@v1
      - name: Add location of python to GH env
        run: |
          echo "PYTHON=${{ steps.setup-python.outputs.python-path }}" >> $GITHUB_ENV
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
        env:
          DO_COMPARISONS: "false"
          
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v7
        with:
          file: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
